version: '3.8'

services:
  api:
    build: .
    command: npm start
    env_file: .env
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - /usr/app/dist
    ports:
      - ${PORT}:${PORT}
